name: BlocksGenerator
version: '1.0'
main: com.Lino.blocksGenerator.BlocksGenerator
api-version: '1.21'
author: Lino
description: Block generator plugin for infinite block farming

commands:
  blockgenerator:
    description: Block generator management command
    usage: /blockgenerator give <player> <generator>
    permission: blocksgenerator.admin
    aliases: [bg, blockgen]

permissions:
  blocksgenerator.admin:
    description: Allows access to all BlocksGenerator commands
    default: op